server:
  port: 8081
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: 311299
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 25281688978-uhjgu1hj2llpvdkj3gqfnld00jm717rl.apps.googleusercontent.com
            client-secret: d0gCTfTFohQC6wCTENdVogDL
            scope: 
            - email
            - profile
          facebook:
            client-id: 308198947456762
            client-secret: cd2bbc2783a9489c94c62b46525873e8
            scope: 
            - email
            - public_profile
  thymeleaf:
    suffix: .html
paypal:
    mode: sandbox
    client:
          app: AbNUz7oHjALdzqEGDpsuaRKlOudu9tV8t6IQ240kQ9idn4EmhttrvIDBgCgqyZEpkJo0lCAR7rXirQSL
          secret: EGCEbUjzbyG0UOByqXnryQsaJy0CyPvZPNSWcWDeJSl7BCd3T-6m1p8ZMNGAM-PiZ8Xlu9aGiR8sv3pF
